packages:
    github.com/JustRussianGuy/GameStats/internal/services/gamestatsService:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            structname: "{{.InterfaceName}}"
            with-expecter: true
        interfaces:
            PlayerStatsStorage: