packages:
    github.com/JustRussianGuy/GameStats/internal/services/gamestatsService:
        config:
            dir: "{{.InterfaceDir}}/mocks"
            filename: "mocks.go"
            pkgname: "mocks"
            structname: "{{.InterfaceName}}"
        interfaces:
            StudentStorage: