// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/JustRussianGuy/GameStats/internal/models"
)

// MockPlayerStatsStorage is an autogenerated mock type for the PlayerStatsStorage type
type MockPlayerStatsStorage struct {
	mock.Mock
}

type MockPlayerStatsStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlayerStatsStorage) EXPECT() *MockPlayerStatsStorage_Expecter {
	return &MockPlayerStatsStorage_Expecter{mock: &_m.Mock}
}

// GetLeaderboard provides a mock function with given fields: ctx, limit
func (_m *MockPlayerStatsStorage) GetLeaderboard(ctx context.Context, limit int) ([]*models.PlayerStats, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetLeaderboard")
	}

	var r0 []*models.PlayerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) ([]*models.PlayerStats, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) []*models.PlayerStats); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.PlayerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerStatsStorage_GetLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLeaderboard'
type MockPlayerStatsStorage_GetLeaderboard_Call struct {
	*mock.Call
}

// GetLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockPlayerStatsStorage_Expecter) GetLeaderboard(ctx interface{}, limit interface{}) *MockPlayerStatsStorage_GetLeaderboard_Call {
	return &MockPlayerStatsStorage_GetLeaderboard_Call{Call: _e.mock.On("GetLeaderboard", ctx, limit)}
}

func (_c *MockPlayerStatsStorage_GetLeaderboard_Call) Run(run func(ctx context.Context, limit int)) *MockPlayerStatsStorage_GetLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *MockPlayerStatsStorage_GetLeaderboard_Call) Return(_a0 []*models.PlayerStats, _a1 error) *MockPlayerStatsStorage_GetLeaderboard_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerStatsStorage_GetLeaderboard_Call) RunAndReturn(run func(context.Context, int) ([]*models.PlayerStats, error)) *MockPlayerStatsStorage_GetLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetPlayerStats provides a mock function with given fields: ctx, playerID
func (_m *MockPlayerStatsStorage) GetPlayerStats(ctx context.Context, playerID string) (*models.PlayerStats, error) {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPlayerStats")
	}

	var r0 *models.PlayerStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.PlayerStats, error)); ok {
		return rf(ctx, playerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.PlayerStats); ok {
		r0 = rf(ctx, playerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PlayerStats)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, playerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPlayerStatsStorage_GetPlayerStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayerStats'
type MockPlayerStatsStorage_GetPlayerStats_Call struct {
	*mock.Call
}

// GetPlayerStats is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID string
func (_e *MockPlayerStatsStorage_Expecter) GetPlayerStats(ctx interface{}, playerID interface{}) *MockPlayerStatsStorage_GetPlayerStats_Call {
	return &MockPlayerStatsStorage_GetPlayerStats_Call{Call: _e.mock.On("GetPlayerStats", ctx, playerID)}
}

func (_c *MockPlayerStatsStorage_GetPlayerStats_Call) Run(run func(ctx context.Context, playerID string)) *MockPlayerStatsStorage_GetPlayerStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlayerStatsStorage_GetPlayerStats_Call) Return(_a0 *models.PlayerStats, _a1 error) *MockPlayerStatsStorage_GetPlayerStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPlayerStatsStorage_GetPlayerStats_Call) RunAndReturn(run func(context.Context, string) (*models.PlayerStats, error)) *MockPlayerStatsStorage_GetPlayerStats_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementDeath provides a mock function with given fields: ctx, playerID
func (_m *MockPlayerStatsStorage) IncrementDeath(ctx context.Context, playerID string) error {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementDeath")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerStatsStorage_IncrementDeath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementDeath'
type MockPlayerStatsStorage_IncrementDeath_Call struct {
	*mock.Call
}

// IncrementDeath is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID string
func (_e *MockPlayerStatsStorage_Expecter) IncrementDeath(ctx interface{}, playerID interface{}) *MockPlayerStatsStorage_IncrementDeath_Call {
	return &MockPlayerStatsStorage_IncrementDeath_Call{Call: _e.mock.On("IncrementDeath", ctx, playerID)}
}

func (_c *MockPlayerStatsStorage_IncrementDeath_Call) Run(run func(ctx context.Context, playerID string)) *MockPlayerStatsStorage_IncrementDeath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlayerStatsStorage_IncrementDeath_Call) Return(_a0 error) *MockPlayerStatsStorage_IncrementDeath_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerStatsStorage_IncrementDeath_Call) RunAndReturn(run func(context.Context, string) error) *MockPlayerStatsStorage_IncrementDeath_Call {
	_c.Call.Return(run)
	return _c
}

// IncrementKill provides a mock function with given fields: ctx, playerID
func (_m *MockPlayerStatsStorage) IncrementKill(ctx context.Context, playerID string) error {
	ret := _m.Called(ctx, playerID)

	if len(ret) == 0 {
		panic("no return value specified for IncrementKill")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, playerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPlayerStatsStorage_IncrementKill_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncrementKill'
type MockPlayerStatsStorage_IncrementKill_Call struct {
	*mock.Call
}

// IncrementKill is a helper method to define mock.On call
//   - ctx context.Context
//   - playerID string
func (_e *MockPlayerStatsStorage_Expecter) IncrementKill(ctx interface{}, playerID interface{}) *MockPlayerStatsStorage_IncrementKill_Call {
	return &MockPlayerStatsStorage_IncrementKill_Call{Call: _e.mock.On("IncrementKill", ctx, playerID)}
}

func (_c *MockPlayerStatsStorage_IncrementKill_Call) Run(run func(ctx context.Context, playerID string)) *MockPlayerStatsStorage_IncrementKill_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPlayerStatsStorage_IncrementKill_Call) Return(_a0 error) *MockPlayerStatsStorage_IncrementKill_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPlayerStatsStorage_IncrementKill_Call) RunAndReturn(run func(context.Context, string) error) *MockPlayerStatsStorage_IncrementKill_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPlayerStatsStorage creates a new instance of MockPlayerStatsStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlayerStatsStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlayerStatsStorage {
	mock := &MockPlayerStatsStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
