// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/models/player_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        uint64                 `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Kills         uint64                 `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        uint64                 `protobuf:"varint,4,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Score         uint64                 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStats) Reset() {
	*x = PlayerStats{}
	mi := &file_api_models_player_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStats) ProtoMessage() {}

func (x *PlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_player_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStats.ProtoReflect.Descriptor instead.
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return file_api_models_player_model_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerStats) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerStats) GetGameId() uint64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *PlayerStats) GetKills() uint64 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerStats) GetDeaths() uint64 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerStats) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type PlayerStatsUpsert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GameId        uint64                 `protobuf:"varint,2,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	Kills         uint64                 `protobuf:"varint,3,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        uint64                 `protobuf:"varint,4,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Score         uint64                 `protobuf:"varint,5,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStatsUpsert) Reset() {
	*x = PlayerStatsUpsert{}
	mi := &file_api_models_player_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStatsUpsert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStatsUpsert) ProtoMessage() {}

func (x *PlayerStatsUpsert) ProtoReflect() protoreflect.Message {
	mi := &file_api_models_player_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStatsUpsert.ProtoReflect.Descriptor instead.
func (*PlayerStatsUpsert) Descriptor() ([]byte, []int) {
	return file_api_models_player_model_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerStatsUpsert) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerStatsUpsert) GetGameId() uint64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *PlayerStatsUpsert) GetKills() uint64 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerStatsUpsert) GetDeaths() uint64 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerStatsUpsert) GetScore() uint64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_api_models_player_model_proto protoreflect.FileDescriptor

const file_api_models_player_model_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/models/player_model.proto\x12\x13gamestats.models.v1\"\x87\x01\n" +
	"\vPlayerStats\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x04R\x06gameId\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x04R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x04 \x01(\x04R\x06deaths\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x04R\x05score\"\x8d\x01\n" +
	"\x11PlayerStatsUpsert\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x17\n" +
	"\agame_id\x18\x02 \x01(\x04R\x06gameId\x12\x14\n" +
	"\x05kills\x18\x03 \x01(\x04R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x04 \x01(\x04R\x06deaths\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x04R\x05scoreB8Z6github.com/JustRussianGuy/GameStats/internal/pb/modelsb\x06proto3"

var (
	file_api_models_player_model_proto_rawDescOnce sync.Once
	file_api_models_player_model_proto_rawDescData []byte
)

func file_api_models_player_model_proto_rawDescGZIP() []byte {
	file_api_models_player_model_proto_rawDescOnce.Do(func() {
		file_api_models_player_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_models_player_model_proto_rawDesc), len(file_api_models_player_model_proto_rawDesc)))
	})
	return file_api_models_player_model_proto_rawDescData
}

var file_api_models_player_model_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_models_player_model_proto_goTypes = []any{
	(*PlayerStats)(nil),       // 0: gamestats.models.v1.PlayerStats
	(*PlayerStatsUpsert)(nil), // 1: gamestats.models.v1.PlayerStatsUpsert
}
var file_api_models_player_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_models_player_model_proto_init() }
func file_api_models_player_model_proto_init() {
	if File_api_models_player_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_models_player_model_proto_rawDesc), len(file_api_models_player_model_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_models_player_model_proto_goTypes,
		DependencyIndexes: file_api_models_player_model_proto_depIdxs,
		MessageInfos:      file_api_models_player_model_proto_msgTypes,
	}.Build()
	File_api_models_player_model_proto = out.File
	file_api_models_player_model_proto_goTypes = nil
	file_api_models_player_model_proto_depIdxs = nil
}
