// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: gamestats_api/gamestats.proto

package gamestats_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GameStatsService_AddEvent_FullMethodName       = "/gamestats.service.v1.GameStatsService/AddEvent"
	GameStatsService_GetPlayerStats_FullMethodName = "/gamestats.service.v1.GameStatsService/GetPlayerStats"
	GameStatsService_GetLeaderboard_FullMethodName = "/gamestats.service.v1.GameStatsService/GetLeaderboard"
)

// GameStatsServiceClient is the client API for GameStatsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameStatsServiceClient interface {
	AddEvent(ctx context.Context, in *AddEventRequest, opts ...grpc.CallOption) (*AddEventResponse, error)
	GetPlayerStats(ctx context.Context, in *PlayerRequest, opts ...grpc.CallOption) (*PlayerStats, error)
	GetLeaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error)
}

type gameStatsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameStatsServiceClient(cc grpc.ClientConnInterface) GameStatsServiceClient {
	return &gameStatsServiceClient{cc}
}

func (c *gameStatsServiceClient) AddEvent(ctx context.Context, in *AddEventRequest, opts ...grpc.CallOption) (*AddEventResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddEventResponse)
	err := c.cc.Invoke(ctx, GameStatsService_AddEvent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameStatsServiceClient) GetPlayerStats(ctx context.Context, in *PlayerRequest, opts ...grpc.CallOption) (*PlayerStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayerStats)
	err := c.cc.Invoke(ctx, GameStatsService_GetPlayerStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameStatsServiceClient) GetLeaderboard(ctx context.Context, in *LeaderboardRequest, opts ...grpc.CallOption) (*LeaderboardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LeaderboardResponse)
	err := c.cc.Invoke(ctx, GameStatsService_GetLeaderboard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameStatsServiceServer is the server API for GameStatsService service.
// All implementations must embed UnimplementedGameStatsServiceServer
// for forward compatibility.
type GameStatsServiceServer interface {
	AddEvent(context.Context, *AddEventRequest) (*AddEventResponse, error)
	GetPlayerStats(context.Context, *PlayerRequest) (*PlayerStats, error)
	GetLeaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error)
	mustEmbedUnimplementedGameStatsServiceServer()
}

// UnimplementedGameStatsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGameStatsServiceServer struct{}

func (UnimplementedGameStatsServiceServer) AddEvent(context.Context, *AddEventRequest) (*AddEventResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddEvent not implemented")
}
func (UnimplementedGameStatsServiceServer) GetPlayerStats(context.Context, *PlayerRequest) (*PlayerStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlayerStats not implemented")
}
func (UnimplementedGameStatsServiceServer) GetLeaderboard(context.Context, *LeaderboardRequest) (*LeaderboardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLeaderboard not implemented")
}
func (UnimplementedGameStatsServiceServer) mustEmbedUnimplementedGameStatsServiceServer() {}
func (UnimplementedGameStatsServiceServer) testEmbeddedByValue()                          {}

// UnsafeGameStatsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameStatsServiceServer will
// result in compilation errors.
type UnsafeGameStatsServiceServer interface {
	mustEmbedUnimplementedGameStatsServiceServer()
}

func RegisterGameStatsServiceServer(s grpc.ServiceRegistrar, srv GameStatsServiceServer) {
	// If the following call panics, it indicates UnimplementedGameStatsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GameStatsService_ServiceDesc, srv)
}

func _GameStatsService_AddEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameStatsServiceServer).AddEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameStatsService_AddEvent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameStatsServiceServer).AddEvent(ctx, req.(*AddEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameStatsService_GetPlayerStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameStatsServiceServer).GetPlayerStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameStatsService_GetPlayerStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameStatsServiceServer).GetPlayerStats(ctx, req.(*PlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameStatsService_GetLeaderboard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LeaderboardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameStatsServiceServer).GetLeaderboard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GameStatsService_GetLeaderboard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameStatsServiceServer).GetLeaderboard(ctx, req.(*LeaderboardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameStatsService_ServiceDesc is the grpc.ServiceDesc for GameStatsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameStatsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "gamestats.service.v1.GameStatsService",
	HandlerType: (*GameStatsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEvent",
			Handler:    _GameStatsService_AddEvent_Handler,
		},
		{
			MethodName: "GetPlayerStats",
			Handler:    _GameStatsService_GetPlayerStats_Handler,
		},
		{
			MethodName: "GetLeaderboard",
			Handler:    _GameStatsService_GetLeaderboard_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gamestats_api/gamestats.proto",
}
