// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/gamestats_api/gamestats.proto

package gamestats_api

import (
	_ "github.com/JustRussianGuy/GameStats/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PlayerEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	VictimId      uint64                 `protobuf:"varint,2,opt,name=victim_id,json=victimId,proto3" json:"victim_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerEvent) Reset() {
	*x = PlayerEvent{}
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerEvent) ProtoMessage() {}

func (x *PlayerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerEvent.ProtoReflect.Descriptor instead.
func (*PlayerEvent) Descriptor() ([]byte, []int) {
	return file_api_gamestats_api_gamestats_proto_rawDescGZIP(), []int{0}
}

func (x *PlayerEvent) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerEvent) GetVictimId() uint64 {
	if x != nil {
		return x.VictimId
	}
	return 0
}

func (x *PlayerEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerRequest) Reset() {
	*x = PlayerRequest{}
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerRequest) ProtoMessage() {}

func (x *PlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerRequest.ProtoReflect.Descriptor instead.
func (*PlayerRequest) Descriptor() ([]byte, []int) {
	return file_api_gamestats_api_gamestats_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type PlayerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      uint64                 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Kills         uint64                 `protobuf:"varint,2,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        uint64                 `protobuf:"varint,3,opt,name=deaths,proto3" json:"deaths,omitempty"`
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStats) Reset() {
	*x = PlayerStats{}
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStats) ProtoMessage() {}

func (x *PlayerStats) ProtoReflect() protoreflect.Message {
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStats.ProtoReflect.Descriptor instead.
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return file_api_gamestats_api_gamestats_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerStats) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerStats) GetKills() uint64 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerStats) GetDeaths() uint64 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerStats) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type LeaderboardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardRequest) Reset() {
	*x = LeaderboardRequest{}
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardRequest) ProtoMessage() {}

func (x *LeaderboardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardRequest.ProtoReflect.Descriptor instead.
func (*LeaderboardRequest) Descriptor() ([]byte, []int) {
	return file_api_gamestats_api_gamestats_proto_rawDescGZIP(), []int{3}
}

func (x *LeaderboardRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type LeaderboardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*PlayerStats         `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResponse) Reset() {
	*x = LeaderboardResponse{}
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResponse) ProtoMessage() {}

func (x *LeaderboardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResponse.ProtoReflect.Descriptor instead.
func (*LeaderboardResponse) Descriptor() ([]byte, []int) {
	return file_api_gamestats_api_gamestats_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderboardResponse) GetPlayers() []*PlayerStats {
	if x != nil {
		return x.Players
	}
	return nil
}

type AddEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddEventResponse) Reset() {
	*x = AddEventResponse{}
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddEventResponse) ProtoMessage() {}

func (x *AddEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_gamestats_api_gamestats_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddEventResponse.ProtoReflect.Descriptor instead.
func (*AddEventResponse) Descriptor() ([]byte, []int) {
	return file_api_gamestats_api_gamestats_proto_rawDescGZIP(), []int{5}
}

func (x *AddEventResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_gamestats_api_gamestats_proto protoreflect.FileDescriptor

const file_api_gamestats_api_gamestats_proto_rawDesc = "" +
	"\n" +
	"!api/gamestats_api/gamestats.proto\x12\x14gamestats.service.v1\x1a\x1dapi/models/player_model.proto\x1a api/google/api/annotations.proto\"e\n" +
	"\vPlayerEvent\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x1b\n" +
	"\tvictim_id\x18\x02 \x01(\x04R\bvictimId\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\",\n" +
	"\rPlayerRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\"n\n" +
	"\vPlayerStats\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x04R\bplayerId\x12\x14\n" +
	"\x05kills\x18\x02 \x01(\x04R\x05kills\x12\x16\n" +
	"\x06deaths\x18\x03 \x01(\x04R\x06deaths\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\"*\n" +
	"\x12LeaderboardRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"R\n" +
	"\x13LeaderboardResponse\x12;\n" +
	"\aplayers\x18\x01 \x03(\v2!.gamestats.service.v1.PlayerStatsR\aplayers\",\n" +
	"\x10AddEventResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x8f\x03\n" +
	"\x10GameStatsService\x12r\n" +
	"\bAddEvent\x12!.gamestats.service.v1.PlayerEvent\x1a&.gamestats.service.v1.AddEventResponse\"\x1b\x82\xd3\xe4\x93\x02\x15:\x01*\"\x10/gamestats/event\x12\x7f\n" +
	"\x0eGetPlayerStats\x12#.gamestats.service.v1.PlayerRequest\x1a!.gamestats.service.v1.PlayerStats\"%\x82\xd3\xe4\x93\x02\x1f\x12\x1d/gamestats/player/{player_id}\x12\x85\x01\n" +
	"\x0eGetLeaderboard\x12(.gamestats.service.v1.LeaderboardRequest\x1a).gamestats.service.v1.LeaderboardResponse\"\x1e\x82\xd3\xe4\x93\x02\x18\x12\x16/gamestats/leaderboardB?Z=github.com/JustRussianGuy/GameStats/internal/pb/gamestats_apib\x06proto3"

var (
	file_api_gamestats_api_gamestats_proto_rawDescOnce sync.Once
	file_api_gamestats_api_gamestats_proto_rawDescData []byte
)

func file_api_gamestats_api_gamestats_proto_rawDescGZIP() []byte {
	file_api_gamestats_api_gamestats_proto_rawDescOnce.Do(func() {
		file_api_gamestats_api_gamestats_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_gamestats_api_gamestats_proto_rawDesc), len(file_api_gamestats_api_gamestats_proto_rawDesc)))
	})
	return file_api_gamestats_api_gamestats_proto_rawDescData
}

var file_api_gamestats_api_gamestats_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_gamestats_api_gamestats_proto_goTypes = []any{
	(*PlayerEvent)(nil),         // 0: gamestats.service.v1.PlayerEvent
	(*PlayerRequest)(nil),       // 1: gamestats.service.v1.PlayerRequest
	(*PlayerStats)(nil),         // 2: gamestats.service.v1.PlayerStats
	(*LeaderboardRequest)(nil),  // 3: gamestats.service.v1.LeaderboardRequest
	(*LeaderboardResponse)(nil), // 4: gamestats.service.v1.LeaderboardResponse
	(*AddEventResponse)(nil),    // 5: gamestats.service.v1.AddEventResponse
}
var file_api_gamestats_api_gamestats_proto_depIdxs = []int32{
	2, // 0: gamestats.service.v1.LeaderboardResponse.players:type_name -> gamestats.service.v1.PlayerStats
	0, // 1: gamestats.service.v1.GameStatsService.AddEvent:input_type -> gamestats.service.v1.PlayerEvent
	1, // 2: gamestats.service.v1.GameStatsService.GetPlayerStats:input_type -> gamestats.service.v1.PlayerRequest
	3, // 3: gamestats.service.v1.GameStatsService.GetLeaderboard:input_type -> gamestats.service.v1.LeaderboardRequest
	5, // 4: gamestats.service.v1.GameStatsService.AddEvent:output_type -> gamestats.service.v1.AddEventResponse
	2, // 5: gamestats.service.v1.GameStatsService.GetPlayerStats:output_type -> gamestats.service.v1.PlayerStats
	4, // 6: gamestats.service.v1.GameStatsService.GetLeaderboard:output_type -> gamestats.service.v1.LeaderboardResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_gamestats_api_gamestats_proto_init() }
func file_api_gamestats_api_gamestats_proto_init() {
	if File_api_gamestats_api_gamestats_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_gamestats_api_gamestats_proto_rawDesc), len(file_api_gamestats_api_gamestats_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_gamestats_api_gamestats_proto_goTypes,
		DependencyIndexes: file_api_gamestats_api_gamestats_proto_depIdxs,
		MessageInfos:      file_api_gamestats_api_gamestats_proto_msgTypes,
	}.Build()
	File_api_gamestats_api_gamestats_proto = out.File
	file_api_gamestats_api_gamestats_proto_goTypes = nil
	file_api_gamestats_api_gamestats_proto_depIdxs = nil
}
